### ISSUE TITLE
Tag the release as it's seen on https://www.astromatic.net/software/skymaker

### ISSUE THREAD

**Issue by Hellseher** [astromatic/skymaker#3]
Hi,

I tried to refresh the package in Guix repository but the source was deleted
from https://www.astromatic.net/download/skymaker/skymaker-3.10.5.tar.gz and
moved/redirected to GitHub.

Would you, please, tag the commit with the latest version? It may ensure that package
maintainers track possible updates.

Thanks,
Oleg

**Comment by eli-schwartz** [comment]
@Hellseher for what it's worth, Gentoo has an archived copy of the original distfile: http://distfiles.gentoo.org/distfiles/cc/skymaker-3.10.5.tar.gz

**Comment by Hellseher** [comment]
@ebertin Is it posible to place a tag 3.10.5 on the commit which was belonged to?

**Comment by ebertin** [comment]
Done! This was a SubVersion tag at the time (10 yrs ago!), but it was not converted automatically apparently.
